mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: ''
  database: mmorpg_deathinventory

redis:
  enable: false
  host: 127.0.0.1
  port: 8080
  password: ''

setting:
  artifact_slot: [9, 10, 11, 12]
  claim_price: 10000000
  max_inventory: 5

gui:
  death1:
    slot: 3
    empty:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
    full:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &7You need &6{price}$ &7to claim"
        - ""
        - "&#a6ffa8Left Click &#fff8c1to claim."
        - "&#90fffdRight Click &#fff8c1to view inventory."
    empty_lock:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
    full_lock:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
        - ""
        - "&#90fffdRight Click &#fff8c1to view inventory."
  death2:
    slot: 4
    empty:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
    full:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &7You need &6{price}$ &7to claim"
        - ""
        - "&#a6ffa8Left Click &#fff8c1to claim."
        - "&#90fffdRight Click &#fff8c1to view inventory."
    empty_lock:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
    full_lock:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
        - ""
        - "&#90fffdRight Click &#fff8c1to view inventory."
  death3:
    slot: 5
    empty:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
    full:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &7You need &6{price}$ &7to claim"
        - ""
        - "&#a6ffa8Left Click &#fff8c1to claim."
        - "&#90fffdRight Click &#fff8c1to view inventory."
    empty_lock:
      material: MINECART
      model: 0
      display_name: "&8Empty"
      lore:
        - ""
        - "&7This slot is empty."
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
    full_lock:
      material: CHEST_MINECART
      model: 0
      display_name: "&#A13333Death &#cc703b#{death}"
      lore:
        - ""
        - "&8Date: &7{date}"
        - ""
        - "&c• &#eca4a7Required rank: &#eeb3ed{rank}"
        - ""
        - "&#90fffdRight Click &#fff8c1to view inventory."

message:
  prefix: "&#FAEDCB[&#DBCDF0DeathInventory&#FAEDCB]"
  gui-title: "Death Inventory"
  date-format: "dd/MM/yyyy | HH:mm"